### PR TITLE
FIx - Issue 7

### PR DESCRIPTION
**Pull request by adebayokehinde**
- Added settings for show liquidation price on chart.

### CODE REVIEW

**Comment by adebayokehinde** [comment]
Fixed! @kappacappa

**Comment by adebayokehinde** [comment]
https://github.com/capofficial/client/issues/7

Done.

**Comment by kappacappa** [comment]
@adebayokehinde there's a new file in the commit, gitpod.yml?

**Comment by adebayokehinde** [comment]
> @adebayokehinde there's a new file in the commit, gitpod.yml?

@kappacappa  .gitpod.yml has been removed!

**Comment by adebayokehinde** [comment]
@kappacappa Everything works fine on my end, kindly make a review so I can move on to the next.

**Pull request closed without merging**
