### PR TITLE
Fix - Issue 23 

### PR DESCRIPTION
**Pull request by adebayokehinde**
Changes made

- Added an onclick function for setting max amount from the user's wallet balance

- Added view balance function to the modal to view each token balance.

### CODE REVIEW

**Comment by kappacappa** [comment]
ref: https://github.com/capofficial/client/issues/23

**Comment by adebayokehinde** [comment]
Do you want me to make changes?

**Comment by kappacappa** [comment]
@adebayokehinde thanks but not exactly the UI we're going for. The available amount should be below the input field. Clicking on that amount should fill the input field. There are edge cases with rounding that need to be dealt with as well to avoid too many decimals from appearing in the input field while making sure the max amount is spent.

**Comment by adebayokehinde** [comment]
> @adebayokehinde thanks but not exactly the UI we're going for. The available amount should be below the input field. Clicking on that amount should fill the input field. There are edge cases with rounding that need to be dealt with as well to avoid too many decimals from appearing in the input field while making sure the max amount is spent.

I'll make changes now!

**Comment by adebayokehinde** [comment]
Changes made @kappacappa

**Comment by adebayokehinde** [comment]
@kappacappa Please make review, I plan on resolving other bounties

**Pull request closed without merging**
