### PR TITLE
Add % corresponding to pool or CAP stake #18

### PR DESCRIPTION
**Pull request by janbsw**

### CODE REVIEW

**Comment by kappacappa** [comment]
> @kappacappa
> 
> Isn't division by zero dealt with automatically? It just shows infinity% but doesn't break anything. I will change the rest, thank you! This was a bit rushed, sorry about that.

Yes, but we don't want to show Infinity to the user :)

**Comment by janbsw** [comment]
I see, will deal with it. What do we want to show the user, because obviously, I won't be able to calculate pool % if $poolBalances[asset] = 0

**Comment by janbsw** [comment]
@kappacappa, this looked like the most intuitive way of dealing with it for the user.

**Comment by kappacappa** [comment]
@janbsw your latest changes contain a spelling mistake ("NA" instead of "N/A" here: https://github.com/capofficial/client/pull/39/commits/07f86cfe11b947b1f347acd20cc421c15aabe434#diff-2859a5299188300443b91cc12df0eba7848e80fdf14e336401abd87d08c08bdbR143).

Also, this will display N/A% in case the balance is zero, we just want to display N/A.

Please keep in mind that all changes should be tested, at least visually and locally on your machine, before submission. Thanks!

**Comment by janbsw** [comment]
@kappacappa I'm so sorry, should all be done now.

**Comment by kappacappa** [comment]
@janbsw Thanks, but there is still a "|| 0" here which does not need to be there: https://github.com/capofficial/client/pull/39/commits/18eb8b3c996c8608acdd6ee54e38fbac96844e61#diff-2859a5299188300443b91cc12df0eba7848e80fdf14e336401abd87d08c08bdbR143

I appreciate your contributions, but I believe the code quality is not there to be eligible for bounties. We're looking for experienced developers who can deliver high quality, tested code from the start.

I encourage you to keep contributing and I'd be happy to look over your future changes as time permits.

**Comment by janbsw** [comment]
@kappacappa I appreciate your honesty, I indeed don't have much experience developing frontends. I'm not doing this for the bounty, so if you don't mind, I'd love if I can continue to contribute, I just love the project and think this will be a great learning opportunity.

Thanks a lot!

**Pull request merged**
