### PR TITLE
Add numberWithCommas function on formatters and integrate on frontend

### PR DESCRIPTION
**Pull request by fhrryDeveloper**

### CODE REVIEW

**Comment by kappacappa** [comment]
@fhrryDeveloper thanks for that. However, commafying numbers would work for the en-US locale, but not for other locales like FR. Other languages have different formats for numbers, as described in https://github.com/capofficial/client/issues/30

It would hence be wiser to use something like this:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

After detecting the user's browser locale.

**Comment by fhrryDeveloper** [comment]
> @fhrryDeveloper thanks for that. However, commafying numbers would work for the en-US locale, but not for other locales like FR. Other languages have different formats for numbers, as described in #30
> 
> It would hence be wiser to use something like this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
> 
> After detecting the user's browser locale.

OK I will update it soon

**Comment by kappacappa** [comment]
@fhrryDeveloper thanks, can you please confirm this has been tested on your local machine and works as expected? If so, I'll merge.

**Comment by fhrryDeveloper** [comment]
> @fhrryDeveloper thanks, can you please confirm this has been tested on your local machine and works as expected? If so, I'll merge.

Yeah of course. I have checked it on my local and it is working well.

**Pull request merged**
